from handlers.admin import (
    AdminAnnouncementDetailHandler,
    AdminAnnouncementStatusHandler,
    AdminAnnouncementsHandler,
    AdminCommunityPostHideHandler,
    AdminCommunityPostsHandler,
    AdminConfigDetailHandler,
    AdminConfigsHandler,
    AdminCourtDetailHandler,
    AdminCourtStatusHandler,
    AdminCourtsHandler,
    AdminEventDetailHandler,
    AdminEventStatusHandler,
    AdminEventsHandler,
    AdminReservationCancelHandler,
    AdminReservationDetailHandler,
    AdminReservationsHandler,
    AdminOperationLogsHandler,
    AdminNotificationBroadcastHandler,
    AdminShopOrderCancelHandler,
    AdminShopOrderCompleteHandler,
    AdminShopOrderDetailHandler,
    AdminShopOrderRefundRejectHandler,
    AdminShopOrdersHandler,
    AdminShopProductDetailHandler,
    AdminShopProductStatusHandler,
    AdminShopProductsHandler,
    AdminStatisticsCourtsHandler,
    AdminStatisticsOverviewHandler,
    AdminStatisticsTimeSlotsHandler,
    AdminStatisticsUsersHandler,
    AdminUserMemberHandler,
    AdminUserPasswordHandler,
    AdminUserRoleHandler,
    AdminUserStatusHandler,
    AdminUsersHandler,
)
from handlers.announcements import AnnouncementDetailHandler, AnnouncementsHandler
from handlers.auth import (
    CaptchaHandler,
    LoginHandler,
    LogoutHandler,
    PasswordHandler,
    ProfileHandler,
    RefreshHandler,
    RegisterHandler,
)
from handlers.community import CommunityPostHideHandler, CommunityPostsHandler
from handlers.courts import CourtsHandler, CourtSlotsHandler
from handlers.events import EventCancelRegistrationHandler, EventDetailHandler, EventRegisterHandler, EventsHandler
from handlers.health import HealthHandler
from handlers.members import MemberTransactionsHandler
from handlers.notifications import (
    NotificationReadAllHandler,
    NotificationReadHandler,
    NotificationUnreadCountHandler,
    NotificationsHandler,
)
from handlers.reservations import (
    CancelReservationHandler,
    MyReservationsHandler,
    ReservationOrderPayHandler,
    ReservationsHandler,
)
from handlers.shop import (
    MyShopOrdersHandler,
    ShopOrderCancelHandler,
    ShopOrderDetailHandler,
    ShopOrderRefundRequestHandler,
    ShopOrdersHandler,
    ShopProductDetailHandler,
    ShopProductsHandler,
)


def build_routes() -> list[tuple[str, object]]:
    return [
        (r"/api/health", HealthHandler),
        (r"/api/admin/health", HealthHandler),
        (r"/api/auth/captcha", CaptchaHandler),
        (r"/api/auth/register", RegisterHandler),
        (r"/api/auth/login", LoginHandler),
        (r"/api/auth/refresh", RefreshHandler),
        (r"/api/auth/logout", LogoutHandler),
        (r"/api/auth/profile", ProfileHandler),
        (r"/api/auth/password", PasswordHandler),
        (r"/api/announcements", AnnouncementsHandler),
        (r"/api/announcements/([^/]+)", AnnouncementDetailHandler),
        (r"/api/notifications", NotificationsHandler),
        (r"/api/notifications/unread-count", NotificationUnreadCountHandler),
        (r"/api/notifications/read-all", NotificationReadAllHandler),
        (r"/api/notifications/([^/]+)/read", NotificationReadHandler),
        (r"/api/member/transactions", MemberTransactionsHandler),
        (r"/api/events", EventsHandler),
        (r"/api/events/([^/]+)", EventDetailHandler),
        (r"/api/events/([^/]+)/register", EventRegisterHandler),
        (r"/api/events/([^/]+)/cancel-registration", EventCancelRegistrationHandler),
        (r"/api/community/posts", CommunityPostsHandler),
        (r"/api/community/posts/([^/]+)/hide", CommunityPostHideHandler),
        (r"/api/shop/products", ShopProductsHandler),
        (r"/api/shop/products/([^/]+)", ShopProductDetailHandler),
        (r"/api/shop/orders", ShopOrdersHandler),
        (r"/api/shop/orders/my", MyShopOrdersHandler),
        (r"/api/shop/orders/([^/]+)/refund-request", ShopOrderRefundRequestHandler),
        (r"/api/shop/orders/([^/]+)/cancel", ShopOrderCancelHandler),
        (r"/api/shop/orders/([^/]+)", ShopOrderDetailHandler),
        (r"/api/courts", CourtsHandler),
        (r"/api/courts/([^/]+)/slots", CourtSlotsHandler),
        (r"/api/reservations", ReservationsHandler),
        (r"/api/reservations/my", MyReservationsHandler),
        (r"/api/reservations/([^/]+)/cancel", CancelReservationHandler),
        (r"/api/reservation-orders/([^/]+)/pay", ReservationOrderPayHandler),
        (r"/api/admin/users", AdminUsersHandler),
        (r"/api/admin/users/([^/]+)/status", AdminUserStatusHandler),
        (r"/api/admin/users/([^/]+)/role", AdminUserRoleHandler),
        (r"/api/admin/users/([^/]+)/member", AdminUserMemberHandler),
        (r"/api/admin/users/([^/]+)/password", AdminUserPasswordHandler),
        (r"/api/admin/courts", AdminCourtsHandler),
        (r"/api/admin/courts/([^/]+)/status", AdminCourtStatusHandler),
        (r"/api/admin/courts/([^/]+)", AdminCourtDetailHandler),
        (r"/api/admin/reservations", AdminReservationsHandler),
        (r"/api/admin/reservations/([^/]+)/cancel", AdminReservationCancelHandler),
        (r"/api/admin/reservations/([^/]+)", AdminReservationDetailHandler),
        (r"/api/admin/statistics/overview", AdminStatisticsOverviewHandler),
        (r"/api/admin/statistics/courts", AdminStatisticsCourtsHandler),
        (r"/api/admin/statistics/time-slots", AdminStatisticsTimeSlotsHandler),
        (r"/api/admin/statistics/users", AdminStatisticsUsersHandler),
        (r"/api/admin/logs", AdminOperationLogsHandler),
        (r"/api/admin/announcements", AdminAnnouncementsHandler),
        (r"/api/admin/announcements/([^/]+)/status", AdminAnnouncementStatusHandler),
        (r"/api/admin/announcements/([^/]+)", AdminAnnouncementDetailHandler),
        (r"/api/admin/notifications/broadcast", AdminNotificationBroadcastHandler),
        (r"/api/admin/events", AdminEventsHandler),
        (r"/api/admin/events/([^/]+)/status", AdminEventStatusHandler),
        (r"/api/admin/events/([^/]+)", AdminEventDetailHandler),
        (r"/api/admin/community/posts", AdminCommunityPostsHandler),
        (r"/api/admin/community/posts/([^/]+)/hide", AdminCommunityPostHideHandler),
        (r"/api/admin/shop/products", AdminShopProductsHandler),
        (r"/api/admin/shop/products/([^/]+)/status", AdminShopProductStatusHandler),
        (r"/api/admin/shop/products/([^/]+)", AdminShopProductDetailHandler),
        (r"/api/admin/shop/orders", AdminShopOrdersHandler),
        (r"/api/admin/shop/orders/([^/]+)/complete", AdminShopOrderCompleteHandler),
        (r"/api/admin/shop/orders/([^/]+)/cancel", AdminShopOrderCancelHandler),
        (r"/api/admin/shop/orders/([^/]+)/refund-reject", AdminShopOrderRefundRejectHandler),
        (r"/api/admin/shop/orders/([^/]+)", AdminShopOrderDetailHandler),
        (r"/api/admin/configs", AdminConfigsHandler),
        (r"/api/admin/configs/([A-Za-z0-9_]+)", AdminConfigDetailHandler),
    ]
