from handlers.recharges import RechargeCustomersHandler, RechargesHandler, RechargeDetailHandler, RechargeCancelHandler, AdminRechargesHandler, AdminRechargeDetailHandler
from handlers.finance import AdminTransactionsHandler, AdminTransactionDetailHandler
from handlers.pickup import ShopPickupCodeHandler, PickupLookupHandler, PickupRedeemHandler
from handlers.staff_booking import (WalkInQuoteHandler, WalkInsHandler, WalkInDetailHandler, WalkInCancelHandler,
    WalkInExtensionQuoteHandler, WalkInExtensionsHandler, StaffPaymentHandler, MockPaymentActionHandler, BalancePaymentHandler, CancelSupplementHandler)
from handlers.booking_operations import (FrontdeskCourtSlotsHandler, ClassifyCourtBlockHandler, MaintenanceCourtBlocksHandler, RecommendationsHandler, RescheduleQuoteHandler, RescheduleHandler,
    ReservationChangesHandler, CourtBlocksHandler, ReleaseCourtBlockHandler, AttendanceHandler, OperationsStatisticsHandler)
from handlers.admin import (
    AdminAnnouncementDetailHandler,
    AdminAnnouncementStatusHandler,
    AdminAnnouncementsHandler,
    AdminCommunityPostHideHandler,
    AdminCommunityPostsHandler,
    AdminConfigDetailHandler,
    AdminConfigsHandler,
    AdminCourtDetailHandler,
    AdminCourtStatusHandler,
    AdminCourtsHandler,
    AdminEventDetailHandler,
    AdminEventStatusHandler,
    AdminEventsHandler,
    AdminReservationCancelHandler,
    AdminReservationDetailHandler,
    AdminReservationsHandler,
    AdminOperationLogsHandler,
    AdminNotificationBroadcastHandler,
    AdminShopOrderCancelHandler,
    AdminShopOrderCompleteHandler,
    AdminShopOrderDetailHandler,
    AdminShopOrderRefundRejectHandler,
    AdminShopOrdersHandler,
    AdminShopProductDetailHandler,
    AdminShopProductStatusHandler,
    AdminShopProductsHandler,
    AdminStatisticsCourtsHandler,
    AdminStatisticsOverviewHandler,
    AdminStatisticsTimeSlotsHandler,
    AdminStatisticsUsersHandler,
    AdminUserMemberHandler,
    AdminUserPasswordHandler,
    AdminUserRoleHandler,
    AdminUserStatusHandler,
    AdminUsersHandler,
)
from handlers.announcements import AnnouncementDetailHandler, AnnouncementsHandler
from handlers.auth import (
    CaptchaHandler,
    LoginHandler,
    LogoutHandler,
    PasswordHandler,
    PasswordResetConfirmHandler,
    PasswordResetRequestHandler,
    ProfileHandler,
    RefreshHandler,
    RegisterHandler,
)
from handlers.community import CommunityPostHideHandler, CommunityPostsHandler
from handlers.courts import CourtsHandler, CourtSlotsHandler, CourtRulesHandler, VenueInfoHandler
from handlers.events import EventCancelRegistrationHandler, EventDetailHandler, EventRegisterHandler, EventsHandler
from handlers.health import HealthHandler
from handlers.members import MemberTransactionsHandler, BookingBalanceHandler
from handlers.notifications import (
    NotificationReadAllHandler,
    NotificationReadHandler,
    NotificationUnreadCountHandler,
    NotificationsHandler,
)
from handlers.reservations import (
    CancelReservationHandler,
    MyReservationsHandler,
    MyReservationDetailHandler,
    ReservationSummaryHandler,
    ReservationOrderPayHandler,
    ReservationsHandler,
)
from handlers.shop import (
    MyShopOrdersHandler,
    ShopOrderCancelHandler,
    ShopOrderDetailHandler,
    ShopOrderRefundRequestHandler,
    ShopOrdersHandler,
    ShopOrderQuoteHandler,
    ShopProductDetailHandler,
    ShopProductsHandler,
)


def build_routes() -> list[tuple[str, object]]:
    return [
        (r'/api/frontdesk/recharge-customers', RechargeCustomersHandler),
        (r'/api/frontdesk/recharges', RechargesHandler),
        (r'/api/frontdesk/recharges/([0-9]+)', RechargeDetailHandler),
        (r'/api/frontdesk/recharges/([0-9]+)/cancel', RechargeCancelHandler),
        (r'/api/admin/recharges', AdminRechargesHandler),
        (r'/api/admin/recharges/([0-9]+)', AdminRechargeDetailHandler),
        (r'/api/admin/transactions', AdminTransactionsHandler),
        (r'/api/admin/transactions/([^/]+)/([0-9]+)', AdminTransactionDetailHandler),
        (r"/api/health", HealthHandler),
        (r"/api/admin/health", HealthHandler),
        (r"/api/auth/captcha", CaptchaHandler),
        (r"/api/auth/register", RegisterHandler),
        (r"/api/auth/login", LoginHandler),
        (r"/api/auth/refresh", RefreshHandler),
        (r"/api/auth/logout", LogoutHandler),
        (r"/api/auth/password-reset/request", PasswordResetRequestHandler),
        (r"/api/auth/password-reset/confirm", PasswordResetConfirmHandler),
        (r"/api/auth/profile", ProfileHandler),
        (r"/api/auth/password", PasswordHandler),
        (r"/api/announcements", AnnouncementsHandler),
        (r"/api/announcements/([^/]+)", AnnouncementDetailHandler),
        (r"/api/notifications", NotificationsHandler),
        (r"/api/notifications/unread-count", NotificationUnreadCountHandler),
        (r"/api/notifications/read-all", NotificationReadAllHandler),
        (r"/api/notifications/([^/]+)/read", NotificationReadHandler),
        (r"/api/member/transactions", MemberTransactionsHandler),
        (r"/api/member/booking-balance", BookingBalanceHandler),
        (r"/api/events", EventsHandler),
        (r"/api/events/([^/]+)", EventDetailHandler),
        (r"/api/events/([^/]+)/register", EventRegisterHandler),
        (r"/api/events/([^/]+)/cancel-registration", EventCancelRegistrationHandler),
        (r"/api/community/posts", CommunityPostsHandler),
        (r"/api/community/posts/([^/]+)/hide", CommunityPostHideHandler),
        (r"/api/shop/products", ShopProductsHandler),
        (r"/api/shop/products/([^/]+)", ShopProductDetailHandler),
        (r"/api/shop/orders", ShopOrdersHandler),
        (r"/api/shop/orders/quote", ShopOrderQuoteHandler),
        (r"/api/shop/orders/my", MyShopOrdersHandler),
        (r"/api/shop/orders/([^/]+)/refund-request", ShopOrderRefundRequestHandler),
        (r"/api/shop/orders/([^/]+)/cancel", ShopOrderCancelHandler),
        (r"/api/shop/orders/([^/]+)", ShopOrderDetailHandler),
        (r"/api/courts", CourtsHandler),
        (r"/api/reservations/recommendations", RecommendationsHandler),
        (r"/api/reservations/([0-9]+)/reschedule/quote", RescheduleQuoteHandler),
        (r"/api/reservations/([0-9]+)/reschedule", RescheduleHandler),
        (r"/api/reservations/([0-9]+)/changes", ReservationChangesHandler),
        (r"/api/admin/court-blocks", CourtBlocksHandler),
        (r"/api/admin/court-blocks/([0-9]+)/type", ClassifyCourtBlockHandler),
        (r"/api/maintenance/court-blocks", MaintenanceCourtBlocksHandler),
        (r"/api/frontdesk/court-slots", FrontdeskCourtSlotsHandler),
        (r"/api/frontdesk/walk-ins/quote", WalkInQuoteHandler),
        (r"/api/frontdesk/walk-ins", WalkInsHandler),
        (r"/api/frontdesk/walk-ins/([0-9]+)", WalkInDetailHandler),
        (r"/api/frontdesk/walk-ins/([0-9]+)/cancel", WalkInCancelHandler),
        (r"/api/frontdesk/walk-ins/([0-9]+)/extensions/quote", WalkInExtensionQuoteHandler),
        (r"/api/frontdesk/walk-ins/([0-9]+)/extensions", WalkInExtensionsHandler),
        (r"/api/payments/([0-9]+)", StaffPaymentHandler),
        (r"/api/payments/([0-9]+)/mock-(confirm|fail)", MockPaymentActionHandler),
        (r"/api/payments/([0-9]+)/balance-pay", BalancePaymentHandler),
        (r"/api/payments/([0-9]+)/cancel", CancelSupplementHandler),
        (r"/api/shop/orders/([0-9]+)/pickup-code", ShopPickupCodeHandler),
        (r"/api/frontdesk/pickups/lookup", PickupLookupHandler),
        (r"/api/frontdesk/pickups/redeem", PickupRedeemHandler),
        (r"/api/admin/court-blocks/([0-9]+)/release", ReleaseCourtBlockHandler),
        (r"/api/admin/reservations/([0-9]+)/attendance", AttendanceHandler),
        (r"/api/admin/statistics/operations", OperationsStatisticsHandler),
        (r"/api/venue", VenueInfoHandler),
        (r"/api/courts/rules", CourtRulesHandler),
        (r"/api/courts/([^/]+)/slots", CourtSlotsHandler),
        (r"/api/reservations", ReservationsHandler),
        (r"/api/reservations/my", MyReservationsHandler),
        (r"/api/reservations/summary", ReservationSummaryHandler),
        (r"/api/reservations/([0-9]+)", MyReservationDetailHandler),
        (r"/api/reservations/([^/]+)/cancel", CancelReservationHandler),
        (r"/api/reservation-orders/([^/]+)/pay", ReservationOrderPayHandler),
        (r"/api/admin/users", AdminUsersHandler),
        (r"/api/admin/users/([^/]+)/status", AdminUserStatusHandler),
        (r"/api/admin/users/([^/]+)/role", AdminUserRoleHandler),
        (r"/api/admin/users/([^/]+)/member", AdminUserMemberHandler),
        (r"/api/admin/users/([^/]+)/password", AdminUserPasswordHandler),
        (r"/api/admin/courts", AdminCourtsHandler),
        (r"/api/admin/courts/([^/]+)/status", AdminCourtStatusHandler),
        (r"/api/admin/courts/([^/]+)", AdminCourtDetailHandler),
        (r"/api/admin/reservations", AdminReservationsHandler),
        (r"/api/admin/reservations/([^/]+)/cancel", AdminReservationCancelHandler),
        (r"/api/admin/reservations/([^/]+)", AdminReservationDetailHandler),
        (r"/api/admin/statistics/overview", AdminStatisticsOverviewHandler),
        (r"/api/admin/statistics/courts", AdminStatisticsCourtsHandler),
        (r"/api/admin/statistics/time-slots", AdminStatisticsTimeSlotsHandler),
        (r"/api/admin/statistics/users", AdminStatisticsUsersHandler),
        (r"/api/admin/logs", AdminOperationLogsHandler),
        (r"/api/admin/announcements", AdminAnnouncementsHandler),
        (r"/api/admin/announcements/([^/]+)/status", AdminAnnouncementStatusHandler),
        (r"/api/admin/announcements/([^/]+)", AdminAnnouncementDetailHandler),
        (r"/api/admin/notifications/broadcast", AdminNotificationBroadcastHandler),
        (r"/api/admin/events", AdminEventsHandler),
        (r"/api/admin/events/([^/]+)/status", AdminEventStatusHandler),
        (r"/api/admin/events/([^/]+)", AdminEventDetailHandler),
        (r"/api/admin/community/posts", AdminCommunityPostsHandler),
        (r"/api/admin/community/posts/([^/]+)/hide", AdminCommunityPostHideHandler),
        (r"/api/admin/shop/products", AdminShopProductsHandler),
        (r"/api/admin/shop/products/([^/]+)/status", AdminShopProductStatusHandler),
        (r"/api/admin/shop/products/([^/]+)", AdminShopProductDetailHandler),
        (r"/api/admin/shop/orders", AdminShopOrdersHandler),
        (r"/api/admin/shop/orders/([^/]+)/complete", AdminShopOrderCompleteHandler),
        (r"/api/admin/shop/orders/([^/]+)/cancel", AdminShopOrderCancelHandler),
        (r"/api/admin/shop/orders/([^/]+)/refund-reject", AdminShopOrderRefundRejectHandler),
        (r"/api/admin/shop/orders/([^/]+)", AdminShopOrderDetailHandler),
        (r"/api/admin/configs", AdminConfigsHandler),
        (r"/api/admin/configs/([A-Za-z0-9_]+)", AdminConfigDetailHandler),
    ]
